### ISSUE TITLE
Change when the feedback form pops

### ISSUE THREAD

**Issue by Mike4o** [telerik/docs-seed#125]
After a research, we found out that the current 30s timer for the feedback form might not be optimal. We checked all documentation sites and noticed that the average time on page has increased in the last years from 1 to 2 minutes (more details below). We also checked the most visited pages for each product and found that the average time on them is from 1 to 3 minutes. This gives us confidence that we can increase the time needed for the feedback form to appear to 45, or even 50 seconds. This should decrease the negative feedback about the form.

More details:
Avg. time on page for the last 6 months for all documentation sites is 0:02:11

docs.telerik.com/ - 0:02:12 
docs.telerik.com/kendo-ui/ - 0:02:05 
 - most visited articles - ~0:01:00
docs.telerik.com/kendo-ui/api/ - 0:01:54
docs.telerik.com/blazor-ui/ - 0:02:39 
 - most visited articles - above 0:02:00
docs.telerik.com/aspnet-core/ - 0:02:05
docs.telerik.com/devtools/aspnet-ajax/ - 0:02:29 
 - most visited articles - from 0:01:00 to 0:03:00
docs.telerik.com/aspnet-mvc/ - 0:02:23
docs.telerik.com/devtools/xamarin/ - 0:02:01
docs.telerik.com/devtools/winforms/ - 0:02:07 
 - most visited articles - from 0:01:00 to 0:03:00
docs.telerik.com/devtools/wpf/ - 0:02:15 
 - most visited articles - from 0:01:00 to 0:03:00
docs.telerik.com/devtools/winui/ - 0:01:07
docs.telerik.com/reporting/ - 0:02:17
 - most visited articles - from 0:01:00 to 0:02:00
docs.telerik.com/report-server/ - 0:02:05
docs.telerik.com/devtools/justmock/ - 0:03:07
docs.telerik.com/teststudio/ - 0:02:36
docs.telerik.com/devtools/teststudiodev - 0:02:40

The only outliers that are under the average are WinUI and Kendo UI for Vue. All the rest are around 2 minutes.

**Comment by pepinho24** [comment]
What about an option that would allow the client to snooze the popup entirely for a given time? 

This will decrease the negative feedback due to the popup even more. And if that client finds the article helpful/unhelpful, they can scroll to the end of the page and vote.

**Comment by imtodor** [comment]
Pep, I see your point, but I think it’s unusual and unexpected to have such a ‘snooze’ behavior for feedback gathering. At least, I haven’t see such. Increasing the popuo time could downcrease those negative feedbacks (not actionable, angry, because of the popup). However, similar behavior could be achieved as follows:

1. The popup shows
2. The customer clicks ‘close’
3. We snooze the popup auto-showing for a week.
4. After one week, the default auto-showing behaviour is triggered again.

**Comment by dimodi** [comment]
Snoozing actually exists already. However, it is not for one week, but *indefinitely* for the given article (the close action is saved in the local storage with no set expiration). I am not sure this is optimal.

We can also discuss whether a close click on one page should have effect on other pages. If something like this is implemented, IMHO the setting should last for 24 hours max.

**Comment by Raisolution** [comment]
> Snoozing actually exists already. However, it is not for one week, but indefinitely for the given article (the close action is saved in the local storage with no set expiration). I am not sure this is optimal.

@dimodi I don't think this is the current implementation. At the moment, clicking the close button and opening the same article again results in the feedback form poping again in 30s. I also support snoozing/caching the close button click (e.g. for a week per article) i.e. having the same behavior for the client as clicking the yes/no buttons.

**Comment by dimodi** [comment]
>> At the moment, clicking the close button and opening the same article again results in the feedback form poping again in 30s.

Yes, this is how it behaves in katana. I was talking about docs-seed :)

https://github.com/telerik/katana/issues/308#issuecomment-746401364

**Comment by Mike4o** [comment]
I think increasing the time for popup and implementing snoozing mechanism are two different things that can both be applied if necessary. Still, can we focus on the time in this issue and proceed with the discussion around that or implement it if everyone believes it can help?

**Comment by pepinho24** [comment]
> I think increasing the time for popup and implementing snoozing mechanism are two different things that can both be applied if necessary. Still, can we focus on the time in this issue and proceed with the discussion around that or implement it if everyone believes it can help?

I agree, we can [fix the timer](https://github.com/telerik/docs-seed/blob/master/_assets/js/feedback.js#L255) and follow the discussion in telerik/katana#308 if we decide to change the UX, UI or obtrusiveness.
