### ISSUE TITLE
CTA Panel interrupts the normal text flow in lists

### ISSUE THREAD

**Issue by yordan-mitev** [telerik/docs-seed#164]
**Describe the bug**
The CTA panel is inserted after the introductory sentence of lists and interrupts the normal text flow.

![image](https://user-images.githubusercontent.com/60105689/122011430-bf32e580-cdc4-11eb-928d-3e788291d68a.png)

The CTA panel should recognize lists and never slip in-between the introductory sentence of a list and the first list item. Alternatively, we should be able to manually control the position of the panel.

**Comment by pepinho24** [comment]
Hi, the positioning of the CTA panel is automatically placed after the second paragraph as we agreed to work for most articles. For such cases where the positioning needs to be different, it can be added manually to the desired positioning as per the instructions here: 
https://github.com/telerik/docs-seed/wiki/Call-To-Action(CTA)-panels#how-to-change-cta-panel-position
