### ISSUE TITLE
Integrate Blazor Repl in documentation

### ISSUE THREAD

**Issue by jivanova** [telerik/docs-seed#173]
- [ ] Deadline for design - 24 Sept https://github.com/telerik/kendo-ux-private/issues/332
- [ ] Deadline for giving instructions of Blazor Repl ( hosting & passing snippet in header functionality ) - 24th September https://github.com/telerik/blazor/issues/2953
- [ ] Implementation in docs-seed 

**Requirements**

Based on the Blazor Repl instruction, we might be able to deliver live editing capabilities and will sync the requirements. Until then, the requirements are for integrating tabstrip and Open with Repl functionality.

- [ ] Add iframe for live editing https://telerik.blazorrepl.com/repl/
- [ ] Add tabstrip layout with Code
- [ ] [TBD by design] Layout in tabstrip
- [ ] [TBD by design] Add button that gets the code snippet and send it to blazor repl (https://github.com/telerik/docs-seed/blob/master/_assets/js/dojo.js#L10)
- [ ] Config.yml instructions for enabling feature => ex: `enable_repl` analogical to enable_dojo

**Comment by pepinho24** [comment]
postMessage API details: https://github.com/telerik/blazor-repl/issues/4

**Comment by pepinho24** [comment]
With https://github.com/telerik/docs-seed/commit/46e4a472f7b049aee443fab9ef542a0eb5bf52d4 commit, certain snippets can be skipped from adding the REPL buttons. 

To do that, add a `<div class="skip-repl"></div>` right before the snippet. Example: 


&lt;div class="skip-repl">&lt;/div>
\`\`\`\`C#
var foo= 5;
\`\`\`\`
\`\`\`\`VB.NET
Dim foo = 5
\`\`\`\`


some text
some other text


&lt;div class="skip-repl">&lt;/div>
\`\`\`\`C#
var skipRepl = true
\`\`\`\`
