### ISSUE TITLE
Implement a Style Guide usage promt when running the local docs build commands 

### ISSUE THREAD

**Issue by dmihaylo** [telerik/docs-seed#176]
We'd like to encourage Progressers to more frequently refer to the Style Guide when creating and maintaining documentation and also make it quicker for them to access it. 

Therefore, let's render a short text in the console that will be triggered by the commands for building the docs locally. 

The content of the text should be **Need help with the docs? Go to the [Style Guide](https://testdocs.telerik.com/style-guide/introduction)**.

**Comment by Iankodj** [comment]
In the console we cannot add links, but only text with URL. 

We could add the following text: 

**Need help with the docs? Go to the Style Guide (https://testdocs.telerik.com/style-guide/introduction).**
