### ISSUE TITLE
Apply missing Security Headers in docs-seed based sites.

### ISSUE THREAD

**Issue by nenchef** [telerik/docs-seed#188]
Use [the Securityheaders.com](https://securityheaders.com/) to check for the missing headers and act respectively, in order to achieve full compliance (like telerik.com has done it: [[see report]](https://securityheaders.com/?q=https%3A%2F%2Fwww.telerik.com%2F&followRedirects=on))

For example, see the failed UI for Core [report](https://securityheaders.com/?q=https%3A%2F%2Fdocs.telerik.com%2Faspnet-core%2Fintroduction&followRedirects=on)

**Comment by pepinho24** [comment]
Regarding the Content-Security-Policy we should check out if inline styles and scripts would stop working. In some documentations in some articles (Test Studio comes to mind now), they needed to add an inline script to one of their pages.

**Comment by Iankodj** [comment]
Security headers applied herer: https://github.com/telerik/docs-content-seed/blob/master/web.config#L54-L59
