### ISSUE TITLE
Unify the Legal resources footer links for the docs-seed product documentations

### ISSUE THREAD

**Issue by dmihaylo** [telerik/docs-seed#189]
We need to unify the footer for all our docs-seed product documentations for the Legal Resources we link to. 

In this way, we'll be able to remove the **Personal Data Collection** articles from the docs left-side navigation as well as the **Copyright** topic after Legal publish it officially in the Legal Resources hub, because we'll have the content users need to be informed about linked from the footer. 

The footer Legal resources have to lead to the following locations: 

* Terms of Use: https://www.telerik.com/about/terms-of-use
* Privacy Center: https://www.progress.com/legal/privacy-policy
* Security Center: https://www.progress.com/security
* Trademarks: https://www.progress.com/legal/trademarks/trademarks-use-policy
* License Agreements: https://www.progress.com/legal
* Code of Conduct: https://www.progress.com/company/code-of-conduct

For more information, refer to the [ASKProgress ticket](https://progress1.service-now.com/sp/?id=ticket&table=sc_req_item&sys_id=3795a8e9db1bb0d06d387a43e2961990&spa=1). 

The attached screenshot is the Standard Footer as approved by the Legal team (available in the ticket too). 

 ![StandardFooter_Legal](https://user-images.githubusercontent.com/13980174/143212156-9eac6655-0192-4316-8481-de9d1ce1e0cb.png)

**Comment by Iankodj** [comment]
The snapshot is not consistent with all telerik.com sites. As we agreed during a call we will follow the design and styles that come from telerik.com with the additional/updated links. 

Check that footer for reference: https://www.telerik.com/kendo-angular-ui/components/

![image](https://user-images.githubusercontent.com/4222379/143228526-1fb63673-18e9-4f1e-b435-fd8b112de609.png)
