### ISSUE TITLE
Dark-theme related issues

### ISSUE THREAD

**Issue by nenchef** [telerik/docs-seed#215]
- [x] After switching from preview to edit mode, all the text has one and the same color. - _rendering issue, not related to the dark theme_

Actual:
<img width="518" alt="darktheme4" src="https://user-images.githubusercontent.com/3844466/166413801-9cc1ea23-8d5d-40bf-84b4-bda27067525d.PNG">

Expected:
<img width="518" alt="darktheme2" src="https://user-images.githubusercontent.com/3844466/166413490-374a78f9-f348-47ed-a180-14963b09bf78.PNG">

- [x] Unreadable code due to blue color http://winslaveblazordocs.dev.progress.com/blazor-ui/components/breadcrumb/overview

![image](https://user-images.githubusercontent.com/7159157/166454633-ac73f8b3-96d6-4a7e-a2fa-8d2a172b285b.png)

- [x] The white theme is applied for a few seconds when navigate to another page - still valid
_There is flickering when switching between pages ( Navigate through component pages in dark mode and you will see loading light theme and then dark: https://winslaveblazordocs.dev.progress.com/blazor-ui/components/autocomplete/overview)_

- [x] Caption class is black
http://winslaveblazordocs.dev.progress.com/blazor-ui/components/breadcrumb/overview

**Comment by pepinho24** [comment]
The first issue about the same color of the code when switching from Preview to Edit mode was there for a long time and is not related to the dark theme. You can double check the live docs with no dark theme where the issue is present - https://docs.telerik.com/kendo-ui/api/javascript/ui/filemanager/configuration/width

**Comment by didiyordanova** [comment]
Code snippets in Xamarin docs do not look okay in dark theme. There is a white border around the snippet. For example: 
https://devdocs.telerik.com/devtools/xamarin/controls/accordion/accordion-key-features#example

**Comment by jivanova** [comment]
- [ ] There is flickering when switching between pages ( Navigate through component pages in dark mode and you will see loading light theme and then dark: https://winslaveblazordocs.dev.progress.com/blazor-ui/components/autocomplete/overview)

**Comment by MilenaCh** [comment]
- [ ] White background is applied to the code snippet in the wrappers doc site
- [ ] Low contrast between the text and background in some snippets(see 'false' parameter in the attached screenshot)

URL: http://kendobuild-staging.dev.progress.com/aspnet-core/compatibility/json-serialization
<img width="536" alt="darktheme5" src="https://user-images.githubusercontent.com/3844466/166450197-29de9e3e-e665-4c8f-b1bf-fd8e35a0daba.PNG">

**Comment by dessyordanova** [comment]
The code snippets in WinForms are also not always readable 
![image](https://user-images.githubusercontent.com/3426684/166465284-edff12ca-d6a1-423a-8765-b5f5e6f80009.png)

**Comment by pepinho24** [comment]
- [ ]  The article container should now be moved up, because the searchbar is removed from its old location

![image](https://user-images.githubusercontent.com/5161281/166645764-e55c2b5c-bd71-4d60-9e05-bf0dd57bd55b.png)

![image](https://user-images.githubusercontent.com/5161281/166645630-a917ce33-26ba-465f-ba98-3537fe4e373a.png)

**Comment by aleksandarevangelatov** [comment]
- [ ] When navigating in the API section the Breadcrumb disappears:
top level:
![image](https://user-images.githubusercontent.com/46348689/167844334-f3355d2e-3adf-44d9-8aac-e1b7d3d03f9d.png)
configuration option selected:
![image](https://user-images.githubusercontent.com/46348689/167844450-c2c1f66e-fdb8-4f6c-a5bd-bec769fc6d79.png)

**Comment by pepinho24** [comment]
- [ ] In dark mode the search bar has a Search icon while in light mode it is not visible
![image](https://user-images.githubusercontent.com/5161281/167876502-c5280cbf-5bfc-4409-b675-02c5aabf6d15.png)
![image](https://user-images.githubusercontent.com/5161281/167876602-7f749e1b-3393-4e68-a5c9-78460ff28c90.png)

**Comment by pepinho24** [comment]
- [ ] With dark theme, links in Blazor docs might not have enough contrast due to the main color 
![image](https://user-images.githubusercontent.com/5161281/168011187-52d040ae-aa8b-42a6-908c-bdee6c948862.png)

**Comment by magdalenaan** [comment]
- [ ] plain code snippets look like hyperlinks https://docs.telerik.com/kendo-ui/controls/navigation/tabstrip/tabs#scrollable-tabs
![2022-05-12_09-19-10](https://user-images.githubusercontent.com/4389590/168004676-7b4fbae4-c05d-4a50-9a0c-c050f793a10c.png)

- [ ] code snippets in hyperlink are not readable on hover https://docs.telerik.com/kendo-ui/controls/navigation/tabstrip/tabs#scrollable-tabs
![2022-05-12_09-20-48](https://user-images.githubusercontent.com/4389590/168004966-387a1d46-3312-4863-bdf9-e440f9ca364c.png)

**Comment by magdalenaan** [comment]
- [ ] Source code in ASP .NET Core (Tag helper tab [here](https://docs.telerik.com/aspnet-core/html-helpers/data-management/grid/overview) ) should improve text colors.
![4F018D29-5888-4EF7-ADCB-82012AE516F1_4_5005_c](https://user-images.githubusercontent.com/52446546/167827974-7608adf1-f0cf-41ca-b53c-cf1cb24690a0.jpeg)
![116749AD-6B89-44F8-A4D1-7E9E0541BF1D](https://user-images.githubusercontent.com/52446546/167828341-f769bdb7-02d3-491e-b534-0f707ceacce6.jpeg)
