### ISSUE TITLE
Custom text inside the cta-panel for MAUI

### ISSUE THREAD

**Issue by didiyordanova** [telerik/docs-seed#229]
**Describe the solution you'd like**

I would like to have the following text inside the cta-panel for the Telerik .NET MAUI docs:

_New to Telerik UI for .NET MAUI?
Kickstart your cross-platform application development with the most comprehensive UI suite for .NET MAUI! To try it out, sign up for a free 30-day trial._

**Comment by didiyordanova** [comment]
@pepinho24 here are the texts for other CTA panels:

small cta-panel: 
New to Telerik UI for .NET MAUI? [Start a free 30-day trial.](https://www.telerik.com/try/ui-for-maui)

control's overview cta-panel:
o This [component name – e.g. Accordion] is part of Telerik UI for .NET MAUI, the most comprehensive UI suite for .NET MAUI! To try it out, sign up for a free 30-day trial and kickstart your cross-platform app development today.

**Comment by pepinho24** [comment]
@didiyordanova please try the `docs-seed` [maui-custom-cta-panels](https://github.com/telerik/docs-seed/tree/maui-custom-cta-panels) branch with the `MAUI docs` [enable-custom-cta-panels](https://github.com/telerik/maui-docs/tree/enable-custom-cta-panels) branch. If everything is okay, we can merge the branches.

**Comment by didiyordanova** [comment]
@pepinho24 
Thank you! I have ran the testdocs build from these branches. 
It seems there are two cta panels for each control's overview page
![2cta-panels-for overview page](https://user-images.githubusercontent.com/39412212/175264170-9706e373-0fdd-43ae-a2ce-f0148ac88e64.png)


How can we solve this issue? Should I include the custom cta panel for each control's overview page? 

Thanks,
Didi

**Comment by pepinho24** [comment]
> @pepinho24 Thank you! I have ran the testdocs build from these branches. It seems there are two cta panels for each control's overview page ![2cta-panels-for overview page](https://user-images.githubusercontent.com/39412212/175264170-9706e373-0fdd-43ae-a2ce-f0148ac88e64.png)
> 
> How can we solve this issue? Should I include the custom cta panel for each control's overview page?
> 
> Thanks, Didi

My bad, an unnecessary markup was left from the verification. I have added the change and now it should appear properly.

**Comment by didiyordanova** [comment]
@pepinho24  now it is okay :) 
I think you can merge the changes and then I will start a new build from master branch on both repos
