### ISSUE TITLE
Knowledge Base search lists its own page

### ISSUE THREAD

**Issue by atkeranov** [telerik/docs-seed#24]
The Knowledge Base search lists its own page. It would be better if it could be excluded from the search.

**To Reproduce**
1. Go to https://docs.telerik.com/report-server/knowledge-base

**Expected behavior**
The first search result should not be the same KB portal page.

**Comment by imtodor** [comment]
Fixed - https://github.com/telerik/docs-seed/commit/400bf4acf5859c3f3f795f66c702e3373dfec100
