### ISSUE TITLE
Allow hiding a section from the navigation tree

### ISSUE THREAD

**Issue by martinivanoff** [telerik/docs-seed#38]
Add a mechanism that allows you to remove a whole section from the navigation tree, but keep its content in the website. 

For example, I would like to hide the RadChart control from the navigation, but I want to keep its articles in the documentation website.

**Comment by imtodor** [comment]
You can do this by through the exclude_navigation property from the _config.yml. For example, if we want to remove a section with name "test", just add the following:

```
exclude_navigation: [test/*]
```
