### ISSUE TITLE
Whitespace is prepended to the beggining of each code block

### ISSUE THREAD

**Issue by attilaantal** [telerik/docs-seed#39]
Example of Rendered HTML. First Span element adds a white space pushing the code to the right.

    <code>
    	<span class="pln">  </span>
    	
    </code>

Visit [ThemeBuilder - Apply](https://docs.telerik.com/devtools/aspnet-ajax/theme-builder/download-and-apply#apply) and check out the code block at point 3 and 4. This issue seems to be present for indented code blocks. Those that are not indented, have no white space at the beggining.

**Comment by Iankodj** [comment]
This comes from the prettifier and snippets should be indented properly in order for the empty space not to be rendered.
