### ISSUE TITLE
Implement cache buster for the web assets

### ISSUE THREAD

**Issue by marin-bratanov** [telerik/docs-seed#44]
**Describe the bug**

When we modify our assets clients cache it leading to issues like this one: [https://www.screencast.com/t/gtrsjrQs](https://www.screencast.com/t/gtrsjrQs).

We can't reasonably expect all our customers to ctrl+f5 our docs.

**To Reproduce**

If you have not cleared your browser cache, and have not fully reloaded our docs, visit any of them after the new searchbar/navbar was implemented and see how it appears when the page is scrolled to the top - it is detached from the top of the page.

**Expected behavior**

We should not require any action from our customers.

Assets can be registered with something like `<link href="stylesheet.css?{{myCacheBusterClass}}">` where we can take the cache buster querystring param from the last modified date of the given asset (we have that lastMod class to take dates from git like when we do the sitemaps). For example, ticks. Of course, this also applies to scripts.

**Comment by marin-bratanov** [comment]
Teams discussion: [https://teams.microsoft.com/l/message/19:eee9cc9d6c9d48a9b0a76da4c0a14e9a@thread.skype/1549584432840?tenantId=db266a67-cbe0-4d26-ae1a-d0581fe03535&groupId=1f1434d4-f107-4c4f-808d-6c58db5e3bb5&parentMessageId=1549584432840&teamName=DevTools%20Team&channelName=Support&createdTime=1549584432840](https://teams.microsoft.com/l/message/19:eee9cc9d6c9d48a9b0a76da4c0a14e9a@thread.skype/1549584432840?tenantId=db266a67-cbe0-4d26-ae1a-d0581fe03535&groupId=1f1434d4-f107-4c4f-808d-6c58db5e3bb5&parentMessageId=1549584432840&teamName=DevTools%20Team&channelName=Support&createdTime=1549584432840)

**Comment by tsvetomir** [comment]
See also https://github.com/envygeeks/jekyll-assets/issues/194#issuecomment-299859537

**Comment by imtodor** [comment]
Fixed.
