### ISSUE TITLE
Jekyll 404 error when building locally

### ISSUE THREAD

**Issue by marin-bratanov** [telerik/docs-seed#50]
Related to #49 - local builds do not work.

I cloned the seed repo anew (even though there were no local changes) and the wrong folder issue went away.

Jekyll still does not build, however, with the same error as when I copied the resources to the correct path myself - it claims it cannot find the config file which is there
![docs 2019-02-24 19 57 33](https://user-images.githubusercontent.com/5746515/53303072-b114d000-386e-11e9-9b6a-a65ba77d2400.png)

**Comment by imtodor** [comment]
Fixed - https://github.com/telerik/docs-seed/commit/0437214ad2ff0d8443f3d70b58c828ec77b47ad9
