### ISSUE TITLE
Search by a single word followed by space

### ISSUE THREAD

**Issue by todorarabadzhiev** [telerik/docs-seed#52]
When typing a single word followed by space in the Search editor there will be no results found, although there will be results if space is removed.
I am used to double-click and copy a word to search for, which selects the word with the following space, and when I paste the selection in Search there will be no results if I don't remove the space.

**Comment by Iankodj** [comment]
This should be fixed with this update: https://github.com/telerik/docs-seed/commit/78f372cbd663eed8b42fe4e0cef3dacad5fc94d6. 

Make sure it is using the latest code.
