### ISSUE TITLE
Knowledge base pager does not function correctly

### ISSUE THREAD

**Issue by dilyantraykov** [telerik/docs-seed#56]
The pager of the knowledge-base page does not function as expected.

With only 30 articles available in the WPF docs, for example, the page shows 156 results and 5+ pages. Clicking on the 5th page in the pager, however, points to a "no results found" page.

1. Go to [https://docs.telerik.com/devtools/wpf/knowledge-base](https://docs.telerik.com/devtools/wpf/knowledge-base)
2. Scroll to the bottom of the page and notice that there are 5 pages (or so).
3. Click the last page and notice the "There were no results found" message.

![wpf-knowledge-base](https://user-images.githubusercontent.com/5472516/55893399-d5c7cb80-5bc0-11e9-85a9-45ae6d2fe1e0.gif)

A similar issue can be observed in the [WinForms KB](https://docs.telerik.com/devtools/winforms/knowledge-base).

![winforms-knowledge-base](https://user-images.githubusercontent.com/5472516/55893634-5d153f00-5bc1-11e9-8191-aeca02cd517e.gif)

**Comment by TanyaDimitrova** [comment]
The same is applicable to the search in the documentation, it is most probably the same search

**Comment by imtodor** [comment]
The issue is caused because of the GSE response and unfortunately we cannot fix it.
