### ISSUE TITLE
Partial build to include subfolders and to ignore _tempconfig.yml

### ISSUE THREAD

**Issue by marin-bratanov** [telerik/docs-seed#77]
The [partial build](https://github.com/telerik/docs-seed#build-site-partially) is a neat feature, but it requires that you add literally every single folder you want built. For example, the `images` folder is ignored when under a folder that is being built, or nested folders (which is very common, especially in older, mature products that need the partial build feature more) are also ignored and you must list them one by one. Without them you don't actually get the content you need.

**Describe the solution you'd like**

Folders that are children of the whitelisted folders of the partial build will also be be built OOB without additional settings.

The `_tempconfig.yml` file must be added to the `.gitignore` when copying assets (`sh copy_local.sh`), so that it does not pop up as an untracked file and mess up your commits.

**Describe alternatives you've considered**

Doing all of this myself is the only alternative. Especially with the folders list it is a bit unreliable because typos are too common when humans write paths.

Deleting the temporary config is not too much of a chore, and it should not break builds down the pipeline, but it will still be nice to have.

**Comment by Iankodj** [comment]
Closed with https://github.com/telerik/docs-seed/pull/78
