### ISSUE TITLE
Add "Copy all code" button for all code snippets

### ISSUE THREAD

**Issue by PavelRPavlov** [telerik/docs-seed#86]
[Competition ](https://help.syncfusion.com/xamarin/button/visualstates) ([another design](https://www.grapecity.com/componentone/docs/xamarin/online-forms/gridCustomizeAppearance.html)) as well as [MSDN ](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#how-standard-format-strings-work) docs provide it. Having such button is widely accepted pattern and customers expect to have it. Not having it may lead to unwanted reaction in customers.

**Comment by imtodor** [comment]
The feature is ready in https://github.com/telerik/docs-seed/tree/copy-code-snippet branch. Please test and let me know if you experience any issues or have feedback to share

**Comment by imtodor** [comment]
https://github.com/telerik/docs-seed/pull/89
