### ISSUE TITLE
GET-ing an URL with a hash has wrong scrolling because of the common Telerik header

### ISSUE THREAD

**Issue by marin-bratanov** [telerik/docs-seed#93]
**Describe the bug**

Landing on the docs with an anchor puts you in limbo because the scroll offset is wrong and you no longer see the heading that we link to.

We use this all the time in tickets.

**To Reproduce**
1. Go to https://docs.telerik.com/blazor-ui/components/grid/overview#sorting 

or any other page in any other docs with an anchor (open the anchor in a new tab, not by clicking it in the current page - we handle that separately and scroll with JS).

You won't see the expected heading and content.

**Expected behavior**

You see the correct heading the link points to (in this example, "Sorting")

**Screenshots**

![Grid for Blazor Overview _ Telerik UI for Blazor -](https://user-images.githubusercontent.com/5746515/78675256-71cc0600-78ed-11ea-839b-e24f9ccd56f7.png)

**Comment by imtodor** [comment]
Pull requests are more than welcome :)

**Comment by marin-bratanov** [comment]
I've no idea how to fix this. I had previously attempted to escalate it through management to the web sites team with their header, but that didn't go anywhere. I am not sure what their requirements for styling of the bar are and whether things like position: sticky would help, and if yes - whether they would work with the header.
Or maybe we would need to use logic similar to the manual scrolling on click in the window.onload event.

**Comment by imtodor** [comment]
I didn't mean you specifically, but rather that everybody could write some new functionality or fix a bug and then open a pull request :) You are correct that this is an old issue and frankly, I haven't investigated it. I'm not sure whether the bug is in our source and we should fix it, or it comes from the main top navigation styles and we could try to work around it just for the docs.

**Comment by marin-bratanov** [comment]
I fear we will have to work around this for the docs on our own. My impression is that the people working on the header tend to focus on the header content and require certain elements and styles to be present on its container (I'm not sure what they are, maybe @PreslavKozovski  knows), and that's about it. Even sites like this one don't have a fix for it and their content/layout is not owned by the tech teams: https://www.telerik.com/support/kb/aspnet-ajax/upload-%28async%29/details/unrestricted-file-upload#r1-2017-to-r2-2017-sp1

**Comment by marin-bratanov** [comment]
Maybe @dimodi could do a PR, to stretch the old front-end dev muscles ;)

**Comment by dimodi** [comment]
https://github.com/telerik/docs-seed/pull/94

**Comment by imtodor** [comment]
The issue is fixed.

**Comment by marin-bratanov** [comment]
Important note: you must run a build for it to happen, its in the static assets, not on a CDN

Useful note: Requires Ctrl+F5 to start working, at least in Blazor (but I think we have some other issues with caching the assets in the first place there).

**Comment by marin-bratanov** [comment]
This is back, easy to test in the following article that is long and has a lot of headings https://docs.telerik.com/blazor-ui/components/grid/manual-operations

Video: 
[video-hash-scroll-offset-is-back.zip](https://github.com/telerik/docs-seed/files/4863935/video-hash-scroll-offset-is-back.zip)

**Comment by dimodi** [comment]
This works on other pages and the only difference I see, is the missing "In this Article" section. My guess is that some JS code is not registered or does not work as a result of the omission. Can you try adding the section?

On a side note, this docs page is a good candidate for splitting into separate examples.

**Comment by marin-bratanov** [comment]
"In this article" comes from the `H2` sections, and if your article has only one of them it does not show up. With more than one scrolling works better for some reason, although it still has some offset when you GET the entire hash, for example clicking on https://winslaveblazordocs.dev.progress.com/blazor-ui/components/grid/manual-operations#grouping-with-onread will lose the heading and the first paragraph (this staging environment has several H2 elements now).

**Comment by dimodi** [comment]
Scrolling to an anchor on initial page load relies on a magic setTimeout number. It looks like this number needs to be increased. I will try that next week.
